# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('primer_apellido', models.CharField(max_length=80)),
                ('segundo_apellido', models.CharField(max_length=80)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('ta', models.FloatField(blank=True, null=True)),
                ('fc', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('otros', models.TextField(blank=True, null=True)),
                ('motivos_consulta', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('antecedentes_patologicos', models.ManyToManyField(to='main.AntecendentesPatologicos')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='antecedentes_patologicos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='indicaciones',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='motivos_consulta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='otros',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='so2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='temp',
        ),
    ]
