# Generated by Django 2.2.6 on 2021-01-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_persona_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Especialidad'),
        ),
        migrations.DeleteModel(
            name='EspecialidadMedico',
        ),
    ]
