# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191018_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=80),
        ),
    ]
