# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181201_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='usuario',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='usuario',
            new_name='paciente',
        ),
    ]
