# Generated by Django 2.2.6 on 2021-01-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210105_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='color',
        ),
    ]
