# Generated by Django 2.2.6 on 2021-01-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_especialidad_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(0, 'MASCULINO'), (1, 'FEMENINO')], null=True),
        ),
    ]
