# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-19 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191019_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidadmedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='main.Medico'),
        ),
    ]
