# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181201_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='so2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
