# Generated by Django 2.2.6 on 2019-11-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_persona_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultorio',
            old_name='nombre',
            new_name='nombre_consultorio',
        ),
    ]
