# Generated by Django 2.2.6 on 2020-03-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191118_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
