# Generated by Django 2.2.6 on 2020-12-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200327_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='color',
            field=models.CharField(default='#3788d8', max_length=20),
        ),
    ]
