# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 16:37
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181202_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
