# Generated by Django 2.2.6 on 2021-02-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210125_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='institucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
