# Generated by Django 2.2.6 on 2021-02-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210202_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=50),
        ),
    ]
