# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 14:22
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_paciente_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
