# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190111_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
