# Generated by Django 2.2.6 on 2021-02-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_paciente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=150),
        ),
    ]
