# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190115_1225'),
    ]

    operations = [

    ]
