# Generated by Django 2.2.6 on 2021-02-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210211_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=500),
        ),
    ]
