# Generated by Django 2.2.6 on 2021-02-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210211_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIncidencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=80)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(max_length=250)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Usuario')),
            ],
        ),
    ]
