# Generated by Django 2.2.6 on 2020-12-17 13:35

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('started_date', models.DateField()),
                ('plan', models.CharField(max_length=250)),
                ('frequency', models.CharField(choices=[('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=50)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
