# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('calendario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cita.Calendario')),
            ],
        ),
        migrations.CreateModel(
            name='ECita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(-1, 'CANCELADA'), (0, 'RESERVADA'), (1, 'CONFIRMADA'), (2, 'TERMINADA')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotBloqueado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.Calendario')),
            ],
        ),
        migrations.CreateModel(
            name='TCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'INICIAL'), (2, 'SEGUIMIENTO')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TFrecuenciaRepeticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.IntegerField(choices=[(0, 'NO REPETIR'), (1, 'TODOS LOS DIAS'), (2, 'SEMANALMENTE'), (3, 'MENSUALMENTE'), (4, 'ANUALMENTE')], unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='slotbloqueado',
            name='frecuencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cita.TFrecuenciaRepeticion'),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cita.ECita'),
        ),
    ]
