# Generated by Django 2.2.6 on 2020-12-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Clínica General', max_length=200)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Medico')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cita.Calendario')),
            ],
        ),
        migrations.CreateModel(
            name='ECita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(-1, 'CANCELADA'), (0, 'RESERVADA'), (1, 'CONFIRMADA'), (2, 'TERMINADA')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventExtendedProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.IntegerField()),
                ('cita', models.IntegerField(blank=True, null=True)),
                ('evento', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'INICIAL'), (2, 'SEGUIMIENTO')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Horario de Consulta', max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('tipo', models.IntegerField(default=0)),
                ('color', models.CharField(default='#3788d8', max_length=20)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cita.Calendario')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='cita.Cita')),
                ('extendedProps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cita.EventExtendedProp')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Medico')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cita.ECita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='main.Medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='main.Paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cita.TCita'),
        ),
    ]
