# Generated by Django 2.2.6 on 2020-12-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dia_semana',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrente',
            field=models.BooleanField(default=0),
        ),
    ]
