# Generated by Django 2.2.6 on 2020-12-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_auto_20201218_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deshabilitado',
            field=models.BooleanField(default=0),
        ),
    ]
