# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_auto_20191021_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHorarioConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SHorarioConsultaDias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'DOMINGO'), (1, 'LUNES'), (2, 'MARTES'), (3, 'MIERCOLES'), (4, 'JUEVES'), (5, 'VIERNES'), (6, 'SABADO')], unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='shorarioconsultadias',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.TDia'),
        ),
        migrations.AddField(
            model_name='shorarioconsultadias',
            name='s_horario_consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.SHorarioConsulta'),
        ),
        migrations.AddField(
            model_name='calendario',
            name='horario_consulta',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cita.SHorarioConsulta'),
            preserve_default=False,
        ),
    ]
