# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_auto_20191012_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='medico_especialidad',
        ),
    ]
