# Generated by Django 2.2.6 on 2020-12-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_event_deshabilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='deshabilitado',
            field=models.BooleanField(default=0),
        ),
    ]
