# Generated by Django 2.2.6 on 2019-10-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_auto_20191022_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='horario_consulta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cita.SHorarioConsulta'),
        ),
    ]
