# Generated by Django 2.2.6 on 2020-12-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_cita_deshabilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcita',
            name='color',
            field=models.CharField(default='#3788d8', max_length=20),
        ),
        migrations.AlterField(
            model_name='tcita',
            name='tipo',
            field=models.CharField(choices=[('PSICOLOGIA', 'PSICOLOGIA'), ('AUTISMO', 'AUTISMO')], max_length=50),
        ),
    ]
