# Generated by Django 2.2.6 on 2021-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0005_auto_20201222_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcita',
            name='tipo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
