# Generated by Django 2.2.6 on 2020-03-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0005_cita_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='No Consulta', max_length=100)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('dia_semana', models.IntegerField()),
                ('tipo', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='shorarioconsultadias',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='shorarioconsultadias',
            name='s_horario_consulta',
        ),
        migrations.RemoveField(
            model_name='slotbloqueado',
            name='calendario',
        ),
        migrations.RemoveField(
            model_name='slotbloqueado',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='horario_consulta',
        ),
        migrations.DeleteModel(
            name='SHorarioConsulta',
        ),
        migrations.DeleteModel(
            name='SHorarioConsultaDias',
        ),
        migrations.DeleteModel(
            name='SlotBloqueado',
        ),
        migrations.DeleteModel(
            name='TDia',
        ),
        migrations.DeleteModel(
            name='TFrecuenciaRepeticion',
        ),
        migrations.AddField(
            model_name='events',
            name='calenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cita.Calendario'),
        ),
    ]
