# Generated by Django 2.2.6 on 2021-01-06 22:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0006_auto_20210104_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcita',
            options={'verbose_name': 'Tipo Cita'},
        ),
        migrations.AlterField(
            model_name='tcita',
            name='color',
            field=colorfield.fields.ColorField(default='#3788d8', max_length=20),
        ),
    ]
