# Generated by Django 2.2.6 on 2020-12-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0007_auto_20200314_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='nombre',
            field=models.CharField(default='Clínica General', max_length=200),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Medico'),
        ),
    ]
