# Generated by Django 2.2.6 on 2021-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0008_cita_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='pagada',
            field=models.BooleanField(default=0),
        ),
    ]
