# Generated by Django 2.2.6 on 2020-12-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200327_1425'),
        ('cita', '0008_auto_20201202_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tipo',
        ),
        migrations.AddField(
            model_name='event',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cita.Cita'),
        ),
        migrations.AddField(
            model_name='event',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.Medico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='calendario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cita.Calendario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cita.ECita'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.Paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cita.TCita'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='titulo',
            field=models.CharField(default='Consulta', max_length=100),
        ),
    ]
