# Generated by Django 2.2.6 on 2021-03-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0009_cita_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventextendedprop',
            name='nombre_doctor',
            field=models.CharField(default='Dr.', max_length=200),
        ),
    ]
