# Generated by Django 2.2.6 on 2020-12-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0009_auto_20201202_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='titulo',
            field=models.CharField(default='Horario de Consulta', max_length=100),
        ),
    ]
