# Generated by Django 2.2.6 on 2020-12-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0010_auto_20201202_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#3788d8', max_length=20),
        ),
    ]
