# Generated by Django 2.2.6 on 2021-03-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0010_eventextendedprop_nombre_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventextendedprop',
            name='evento_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventextendedprop',
            name='evento_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
