# Generated by Django 2.2.6 on 2020-12-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0011_event_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extended_props',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
