# Generated by Django 2.2.6 on 2021-03-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0011_auto_20210304_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#99ADC1', max_length=20),
        ),
    ]
