# Generated by Django 2.2.6 on 2020-12-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0012_event_extended_props'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extended_props',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
