# Generated by Django 2.2.6 on 2021-04-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0012_auto_20210331_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='pagada',
        ),
    ]
