# Generated by Django 2.2.6 on 2020-12-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0013_auto_20201203_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventExtendedProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.IntegerField()),
                ('cita', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='extended_props',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cita.EventExtendedProp'),
        ),
    ]
