# Generated by Django 2.2.6 on 2021-05-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0013_remove_cita_pagada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='deshabilitado',
        ),
        migrations.RemoveField(
            model_name='eventextendedprop',
            name='evento',
        ),
        migrations.AddField(
            model_name='cita',
            name='color',
            field=models.CharField(default='#99ADC1', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='dia_semana',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='extendedProps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cita.EventExtendedProp'),
        ),
        migrations.AddField(
            model_name='cita',
            name='posicion_turno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cita',
            name='recurrente',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='cita',
            name='titulo',
            field=models.CharField(default='Horario de Consulta', max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='main.Paciente'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
