# Generated by Django 2.2.6 on 2020-12-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0014_auto_20201203_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='extended_props',
            new_name='extendedProps',
        ),
    ]
