# Generated by Django 2.2.6 on 2020-12-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0015_auto_20201204_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
