# Generated by Django 2.2.6 on 2020-12-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0018_auto_20201204_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventextendedprop',
            name='evento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='cita.Cita'),
        ),
    ]
