# Generated by Django 2.2.6 on 2020-12-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0019_auto_20201204_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dia_semana',
        ),
    ]
