# Generated by Django 2.2.6 on 2020-12-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0020_remove_event_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
