# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_comienzo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedenteAlergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Alergia')),
                ('antecedente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Antecedente')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SAntecedente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Medico')),
            ],
        ),
        migrations.CreateModel(
            name='SAntecedenteTAlergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('s_antecedente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.SAntecedente')),
            ],
        ),
        migrations.CreateModel(
            name='TAlergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='santecedentetalergia',
            name='t_alergia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.TAlergia'),
        ),
        migrations.AddField(
            model_name='antecedente',
            name='historia_clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.HistoriaClinica'),
        ),
        migrations.AddField(
            model_name='alergia',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.TAlergia'),
        ),
    ]
