# Generated by Django 2.2.6 on 2020-12-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='diagnostico_medico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='escolaridad_menor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='grado_cursa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='neuropsicologia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='neuroterapia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='nombre_colegio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='nombre_entrevistador',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='observaciones_generales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='ocupacion_madre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='ocupacion_padre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='profesional_cargo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='psicologia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='psicopedagogia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='remitido_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='servicio_solicitado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='telefono_madre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='telefono_padre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='terapia_fisica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='terapia_lenguaje',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='terapia_ocupacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='terapias',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='valoracion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Paciente'),
        ),
    ]
