# Generated by Django 2.2.6 on 2020-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20201229_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='escolaridad_menor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='estado_civil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_cita',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='folio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='grado_cursa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='nombre_colegio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='nombre_entrevistador',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='nombre_madre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='nombre_padre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='ocupacion_madre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='ocupacion_padre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='profesional_cargo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='remitido_por',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='servicio_solicitado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='telefono_madre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='telefono_padre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='terapias',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='valoracion',
            field=models.CharField(max_length=250),
        ),
    ]
