# Generated by Django 2.2.6 on 2020-12-30 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20201229_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='terapias',
            new_name='costo_terapias',
        ),
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='valoracion',
            new_name='costo_valoracion',
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='main.Paciente'),
        ),
    ]
