# Generated by Django 2.2.6 on 2020-12-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20201230_0659'),
    ]

    operations = [

    ]
