# Generated by Django 2.2.6 on 2021-01-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_auto_20210114_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='grado_cursa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='nombre_colegio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='ocupacion_madre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='ocupacion_padre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
