# Generated by Django 2.2.6 on 2021-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_auto_20210331_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='folio',
            field=models.IntegerField(default=0),
        ),
    ]
