# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NotaPadecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NotaPadecimientoSignoVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SignoVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SNotaPadecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('s_consulta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.SConsulta')),
            ],
        ),
        migrations.CreateModel(
            name='SNotaPadecimientoTSignoVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('s_nota_padecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.SNotaPadecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='TConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TSignoVital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='snotapadecimientotsignovital',
            name='t_signo_vital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.TSignoVital'),
        ),
        migrations.AddField(
            model_name='signovital',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.TSignoVital'),
        ),
    ]
