# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('consulta', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sconsulta',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Medico'),
        ),
        migrations.AddField(
            model_name='notapadecimientosignovital',
            name='nota_padecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.NotaPadecimiento'),
        ),
        migrations.AddField(
            model_name='notapadecimientosignovital',
            name='signo_vital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.SignoVital'),
        ),
        migrations.AddField(
            model_name='notapadecimiento',
            name='consulta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.Consulta'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='historia_clinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.HistoriaClinica'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Medico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.TConsulta'),
        ),
    ]
