# Generated by Django 2.2.6 on 2021-03-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LugarGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('entidad', models.CharField(max_length=250)),
                ('recibo', models.CharField(max_length=250)),
                ('factura', models.CharField(blank=True, max_length=250, null=True)),
                ('total', models.FloatField(default=0.0)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='contabilidad.TipoPago')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='contabilidad.LugarGasto')),
                ('subcuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='contabilidad.SubCuenta')),
            ],
        ),
    ]
