# Generated by Django 2.2.6 on 2021-05-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_tabuladorprecios'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabuladorprecios',
            name='tipo_cobro',
            field=models.CharField(choices=[('EVENTO', 'Por Evento'), ('TOTAL', 'Precio Total')], default=('EVENTO', 'Por Evento'), max_length=50),
        ),
    ]
